name: marqoum
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  provider: ^4.3.1
  hive: ^1.4.2
  hive_flutter: ^0.3.1
  path_provider: ^1.6.7
  google_fonts: ^1.0.0
  flutter_svg: ^0.17.4
  fab_circular_menu: ^1.0.0
  native_pdf_view: ^3.6.2
  shared_preferences: ^0.5.7+1
  flutter_sound: ^4.0.4+1
  flutter_spinkit: ^4.1.2+1
  flutter_launcher_icons: ^0.7.5
  flutter_native_splash: ^0.1.9
  flat_icons_flutter: ^1.0.2 
  intl: ^0.16.1
  permission_handler: ^5.0.0+hotfix.6
  esys_flutter_share: ^1.0.2
  flutter_share: ^1.0.2+1
  font_awesome_flutter: ^8.8.1
  animate_do: ^1.7.2
  flutter_inner_drawer: ^0.5.7+2
  majesty: ^0.0.3
  floating_bottom_navigation_bar: ^1.4.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  build_runner: ^1.10.0
  hive_generator: ^0.7.1


  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
dependency_overrides:
  analyzer: '0.39.14'

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: NeoSans
       fonts:
         - asset: assets/Fonts/NeoSansArabic.ttf
         - asset: assets/Fonts/NeoSansArabicbold.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
